feat: implements stats-service
fixercom/java-explore-with-me pull request #4
Opened 2023-04-08 11:49 UTC by fixercom

2023-04-09 09:37 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай обсудим комментарии и будет зачет =)

2023-04-09 09:37 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/main/MainApp.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewm.main", "ru.practicum.ewm.stats.client"})
Для чего это?

2023-04-09 09:37 UTC, krylov-sergey-sergeevich commented on main-service/pom.xml
> +    <packaging>jar</packaging>
Для чего это?

2023-04-09 09:37 UTC, krylov-sergey-sergeevich commented on main-service/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
${project.version}

2023-04-09 09:37 UTC, krylov-sergey-sergeevich commented on stats-service/client/pom.xml
> +            <artifactId>dto</artifactId>
можно добавить
<version>${project.version}</version>

2023-04-09 09:37 UTC, krylov-sergey-sergeevich commented on stats-service/client/pom.xml
> +            <artifactId>spring-boot-starter-web</artifactId>
можно добавить
`<optional>true</optional>`

2023-04-09 09:37 UTC, krylov-sergey-sergeevich commented on stats-service/client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +        restTemplate = new RestTemplateBuilder()
Можно еще так, не нужно переделывать:
 HttpClient.newBuilder()
				.connectTimeout(Duration.ofSeconds(2))
				.build();
	}

2023-04-09 09:52 UTC, fixercom commented on main-service/src/main/java/ru/practicum/ewm/main/MainApp.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewm.main", "ru.practicum.ewm.stats.client"})
Привет Сергей! Это я здесь создавал контроллер испытывал созданный клиент. Никак не мог подключить клиент потому-что основное приложение у меня в пакете ru.practicum.ewm.main, а клиент в ru.practicum.ewm.stats.client. Я так понял что по умолчанию @SpringBootApplication сканит только тот пакет в котором лежит класс с этой анноацией. И смог подключить только таким образом. И вообще я никак не пойму как правильно в многомодульных приложениях именовать пакеты, может быть надо было их все в один пакет отправлять?

2023-04-09 09:59 UTC, fixercom commented on main-service/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
Забыл убрать в этом модуле:)  у меня в главном pom уже завязано все на глобальную переменную через dependencyManagment чтобы здесь вообще не указывать версии.

2023-04-09 10:04 UTC, fixercom commented on stats-service/client/pom.xml
> +            <artifactId>dto</artifactId>
Здесь тоже вынесено через dependencyManagment версия в родительском pom (а там уже завязано на переменную) или так лучше не делать?

2023-04-09 10:40 UTC, fixercom commented on stats-service/client/pom.xml
> +            <artifactId>spring-boot-starter-web</artifactId>
Добавил. Это как работает? Чтобы главный сервер второй раз не тянул эти зависимость когда мы будем подключать эту библиотеку?

2023-04-09 10:55 UTC, fixercom commented on main-service/pom.xml
> +    <packaging>jar</packaging>
Думал обязательно надо указывать тип упаковки или pom или jar и т.п. Хотя смотрю в модулях статистики не указывал и все работает:)

2023-04-10 07:18 UTC, krylov-sergey-sergeevich commented on stats-service/client/pom.xml
> +            <artifactId>spring-boot-starter-web</artifactId>
<optional>true</optional> это элемент в файле pom.xml для пакетного менеджера Apache Maven. Этот элемент определяет, является ли зависимость опциональной для проекта. Если установлено значение true, то зависимость не является обязательной для компиляции или развертывания проекта. Это означает, что если у вас есть зависимость, указанная с атрибутом <optional>true</optional>, ваш проект все еще может собираться и работать, даже если эта зависимость недоступна во время выполнения.

2023-04-10 07:22 UTC, krylov-sergey-sergeevich commented on stats-service/client/pom.xml
> +            <artifactId>dto</artifactId>
Можно и так, даже это в чем то лучше

2023-04-10 07:28 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/main/MainApp.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum.ewm.main", "ru.practicum.ewm.stats.client"})
Привет, в многомодульных приложениях я рекомендую выбрать базовый пакет например ru.practicum.ewm и там создать класс запуска приложения, и все остальные пакеты должны быть ниже него по пакетной структуре (даже в других модулях) и тогда не придется прописывать список пакетов

2023-04-10 07:32 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-04-10 07:35 UTC, merged