Main svc
fixercom/java-explore-with-me pull request #5
Opened 2023-04-17 14:29 UTC by fixercom

2023-04-19 04:25 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа, буквально пару вопросов и зачет будет

2023-04-19 04:25 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/compilation/dto/CompilationDto.java
> +    List<EventShortDto> events;
private final для полей?

2023-04-19 04:25 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/compilation/dto/PublicCompilationFilter.java
> +public class PublicCompilationFilter {
модификаторы доступа

2023-04-19 04:25 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
"yyyy-MM-dd HH:mm:ss" - везде повторяется

2023-04-19 04:25 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    @AttributeOverrides(value = {
Ух, немного усложнено) А почему просто два поля не понравились?)

2023-04-19 10:11 UTC, fixercom commented on main-service/src/main/java/ru/practicum/ewm/compilation/dto/CompilationDto.java
> +    List<EventShortDto> events;
Постоянно забываю почему-то в ДТОшках :)

2023-04-19 10:11 UTC, fixercom commented on main-service/src/main/java/ru/practicum/ewm/compilation/dto/PublicCompilationFilter.java
> +public class PublicCompilationFilter {
Добавил

2023-04-19 10:11 UTC, fixercom commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventFullDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Вынес в DateUtils статическую переменную

2023-04-19 10:19 UTC, fixercom commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    @AttributeOverrides(value = {
Понравились:) меня спугнуло то что Location выделена в отдельную DTO, изначально и хотел просто полями сделать, а потом подумал вдруг хотят чтобы именно отдельная сущность была. Изменил на обычные поля.

2023-04-20 05:36 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-04-20 06:24 UTC, merged